# Fabric8 resource fragment 
# http://maven.fabric8.io/#resource-fragments
#
# we want to specify a liveness/readyness probe with a URI differing from the K8s default of /health :
spec:
  replicas: 1
  template:
    spec:
      containers:
        - livenessProbe:
            httpGet:
              path: /actuator/health/
              port: 8989
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/
              port: 8989
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 5